#!/usr/bin/env python3
#

from argparse                           import ArgumentParser, RawTextHelpFormatter
from trellohelp                         import TrelloHelp

class Taker(object):
    def main(self, args):
        '''
        '''
        th = TrelloHelp()

        sru_board = th.board_find(f'SRU Cycle {args.cycle}')
        the_list = th.list_find_on_board(sru_board, 'On Deck')
        for card in th.trello.list_cards(the_list['id']):
            if card['name'].startswith('Crank ') and ' kernel' in card['name']:
                handle = card['name'].split(' ')[2].replace('/', ':')
                if handle == args.handle:
                    target_list = th.list_find_on_board(sru_board, 'In Progress')
                    th.trello.card_update(card['id'], idList=target_list['id'], pos='bottom')
                    th.trello.card_addmember(card['id'], th.me['id'])
                    break


if __name__ == '__main__':
    app_description = '''
    '''
    app_epilog = '''
    '''

    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawTextHelpFormatter)
    parser.add_argument('cycle', help='SRU cycle tag (YYYY.MM.DD)')
    parser.add_argument('handle', help='<series>:<package>')
    args = parser.parse_args()

    retval = Taker().main(args)

    exit(retval)
