#!/usr/bin/env python3
#

from argparse                           import ArgumentParser, RawTextHelpFormatter
from trellohelp                         import TrelloHelp

class OnDeck(object):
    def main(self, args):
        '''
        '''
        th = TrelloHelp()
        board_name = f'SRU Cycle {args.cycle}'

        # cranky wod (what's on deck?)
        #
        the_list = th.list_find_on_board(th.board_find(board_name), 'On Deck')
        for card in th.trello.list_cards(the_list['id']):
            if card['name'].startswith('Crank ') and ' kernel' in card['name']:
                handle = card['name'].split(' ')[2].replace('/', ':')
                print(f'{handle}')


if __name__ == '__main__':
    app_description = '''
    '''
    app_epilog = '''
    '''

    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawTextHelpFormatter)
    parser.add_argument('cycle', help='SRU cycle tag (YYYY.MM.DD)')
    args = parser.parse_args()

    retval = OnDeck().main(args)

    exit(retval)
